import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import './HistoryScreen.css';
export function HistoryScreen({ onBack, allTimeStats }) {
    const sortedStats = Object.entries(allTimeStats)
        .sort(([, a], [, b]) => b - a);
    const totalGames = Object.values(allTimeStats).reduce((sum, count) => sum + count, 0);
    return (_jsxs("div", { className: "history-screen", children: [_jsxs("div", { className: "history-header", children: [_jsx("button", { className: "back-btn", onClick: onBack, children: "\u2190" }), _jsx("h1", { children: "\uD83D\uDCCA \uC804\uCCB4 \uD788\uC2A4\uD1A0\uB9AC" }), _jsx("div", { className: "spacer" })] }), _jsxs("div", { className: "history-stats", children: [_jsxs("div", { className: "stat-card", children: [_jsx("span", { className: "stat-label", children: "\uCD1D \uB77C\uC6B4\uB4DC" }), _jsx("span", { className: "stat-value", children: totalGames })] }), _jsxs("div", { className: "stat-card", children: [_jsx("span", { className: "stat-label", children: "\uCC38\uC5EC\uC790" }), _jsx("span", { className: "stat-value", children: sortedStats.length })] })] }), _jsxs("div", { className: "ranking-list", children: [_jsx("h2", { children: "\uD83C\uDFC6 \uB7AD\uD0B9" }), sortedStats.length > 0 ? (_jsx("div", { className: "ranking-items", children: sortedStats.map(([name, count], index) => (_jsxs("div", { className: "ranking-item", children: [_jsxs("div", { className: "ranking-medal", children: [index === 0 && '🥇', index === 1 && '🥈', index === 2 && '🥉', index > 2 && _jsx("span", { className: "ranking-number", children: index + 1 })] }), _jsxs("div", { className: "ranking-info", children: [_jsx("span", { className: "ranking-name", children: name }), _jsxs("span", { className: "ranking-count", children: [count, "\uD68C"] })] }), _jsx("div", { className: "ranking-bar", children: _jsx("div", { className: "ranking-fill", style: {
                                            width: `${(count / Math.max(...Object.values(allTimeStats))) * 100}%`,
                                        } }) })] }, name))) })) : (_jsx("p", { className: "no-data", children: "\uC544\uC9C1 \uAE30\uB85D\uC774 \uC5C6\uC2B5\uB2C8\uB2E4. \uAC8C\uC784\uC744 \uC2DC\uC791\uD574\uBCF4\uC138\uC694!" }))] }), _jsx("button", { className: "back-full-btn", onClick: onBack, children: "\uB3CC\uC544\uAC00\uAE30" })] }));
}
